# Lab 1b: Introduction to Jupyter, NumPy, and Matplotlib

## Task 0: Introduction to Jupyter Notebook

### Jupyter Notebook Basics

1. Create your first notebook.
1. Click on the Home tab in your web browser with the list of files in the Lab1b directory.
1. In the upper right corner, click "New" then "Notebook" then select a "Python 3" kernel in the new browser tab that opens up.
   <img src="images/lab1b_new_nb_1.png" alt="new notebook 1/2" width="600"/><br/>
   <img src="images/lab1b_new_nb_2.png" alt="new notebook 2/2" width="300"/>

1. Click on Untitled at the top left of the notebook and rename your notebook Lab1bTest
1. In your first Cell type `## Hello World` and press Run (`Shift+Enter`).
1. Change your first cell type to markdown and press Run (`Shift+Enter`).
1. [Markdown quick reference](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)
1. Create a new cell and type `print("Hello World")` into it and press Run (`Shift+Enter`).
1. Include "Lab1bTest" in your submission.

<img src="images/bar.png" alt="heading"/>

## Task 1: Introduction to NumPy

For Tasks 1 and 2 please complete them by editing a copy of this notebook.

### 1a) Create a NumPy Array

1. Import `test.csv` located in the Lab1b data subfolder into a ndarray using [NumPy genfromtxt](https://numpy.org/devdocs/reference/generated/numpy.genfromtxt.html), [More info](https://numpy.org/devdocs/user/basics.io.genfromtxt.html)
   1. You will need to specify the file path and indicate that the delimiter is a comma (the ',' character).
2. Print data [printing arrays](https://numpy.org/doc/stable/user/quickstart.html#printing-arrays)


In [2]:
import numpy as np

In [ ]:
### BEGIN SOLUTION


### END SOLUTIO'

# Expected'output
# [[1'.'16.  4.  5.]
# [ 4. 10. 10.  3.]
# [ 10.  4. 17. 12.]
# [ 6. 12.  1. 16.]
# [14. 15.  1. 12.]
# [11. 15. 19.  2.]]

[[15. 16.  4.  5.]
 [ 4. 10. 10.  3.]
 [10.  4. 17. 12.]
 [ 6. 12.  1. 16.]
 [14. 15.  1. 12.]
 [11. 15. 19.  2.]]


### 1b. Explore NumPy array

#### Using the below links ↓ and NumPy documentation to complete the following tasks:

[NumPy ndarray](https://numpy.org/devdocs/reference/arrays.ndarray.html)  
[Array indexing](https://numpy.org/devdocs/user/basics.indexing.html)

1. Print the shape of the array from test.csv.
2. Print just the 3rd column (column with index 2) of the array from test.csv.
3. Print just the 5th row of the array from test.csv.
4. Use a single ndarray method find the min of each column of the array from test.csv and print it
5. Use a single ndarray method to find the max of each row of the array from test.csv and print it
6. Use a single ndarray method to find the mean of each column of the array from test.csv and print it
7. Use a single ndarray method to find the sum of each row of the array from test.csv and print it
8. What is the shape of array2?
9. In one line use a ndarray method to convert array2 to a two dimensional array (i.e. remove the **singleton dimension** — the dimension that only has a "1 shape").


In [ ]:
# 1. Print the shape of the array from test.csv.

### BEGIN SOLUTION


### END SOLUTION

# Expected output
# (6, 4)

In [ ]:
# 2. Print just the 3rd column (column with index 2) of the array from test.csv.

### BEGIN SOLUTION


### END SOLUTION

# Expected output
# [ 4. 10. 17.  1.  1. 19.]

In [ ]:
# 3. Print just the 5th row of the array from test.csv.

### BEGIN SOLUTION


### END SOLUTION

# Expected output
# [14. 15.  1. 12.]

In [ ]:
# 4. Use a single ndarray method find the min of each column of the array from test.csv and print it

### BEGIN SOLUTION


### END SOLUTION

# Expected output
# [4. 4. 1. 2.]

In [ ]:
# 5. Use a single ndarray method to find the max of each row of the array from test.csv and print it

### BEGIN SOLUTION


### END SOLUTION

# Expected output
# [16. 10. 17. 16. 15. 19.]

In [ ]:
# 6. Use a single ndarray method to find the mean of each column of the array from test.csv and print it

### BEGIN SOLUTION


### END SOLUTION

# Expected output
# [10.         12.          8.66666667  8.33333333]

In [ ]:
# 7. Use a single ndarray method to find the sum of each row of the array from test.csv and print it

### BEGIN SOLUTION


### END SOLUTION

# Expected output
# [40. 27. 43. 35. 42. 47.]

In [ ]:
# array2 given
array2 = np.array([[[0], [2], [4]], [[1], [3], [5]]])

In [ ]:
# 8. What is the shape of array2?

### BEGIN SOLUTION


### END SOLUTION

# Expected output
# (2, 3, 1)

In [ ]:
# 9. In one line use a ndarray method to convert array2 to a two dimensional array
#    (i.e. remove the singleton dimension — the dimension that only has a "1 shape").

### BEGIN SOLUTION


### END SOLUTION

# Expected output
# (2, 3)

## Task 2: Matplotlib Basics

**Let me know when you reach this point.**

### 2a. Plot the data in a single plot

Using the [Matplotlib](https://matplotlib.org/) documentation, visualize the dataset with Matplotlib. All charts should include a title, axis labels and a legend when applicable.

1. Import `lab1.csv` into a ndarray using genfromtxt.
2. Set figure size to 12x8. Use either [plt.figure](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.figure.html) or [rcParams](https://matplotlib.org/3.1.0/tutorials/introductory/customizing.html#matplotlib-rcparams) (_search for `figure.figsize`_).
3. Create a cartesian line graph of last column (on the X axis) vs the 2nd column (Y axis) using a red dashed line. [matplotlib.pyplot introduction](https://matplotlib.org/tutorials/introductory/pyplot.html)
   1. Include a title and axis labels.


In [ ]:
### BEGIN SOLUTION


### END SOLUTION

### 2b. Plot the data in multiple subplots

Create 6 graphs in 2 columns and 3 rows using [subplots](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.subplot.html).

1. Row 1 is two subplots (a scatterplot and a line graph) of the 2nd column graphed on the x-axis VS the 1st column graphed on the y-axis
2. Row 2 is two subplots (a scatterplot and a line graph) of the 3rd column (x-axis) VS the 2nd column (y-axis)
3. Row 3 is two subplots (a scatterplot and a line graph) of the 3rd column (x-axis) VS the 1st column (y-axis)
4. Include a title and axis labels for each subplot. You can refer to the 1st column as `X`, the 2nd as `Y`, and the 3rd as `Z`.
5. To insure there is enough space between subplots use [subplots_adjust](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.subplots_adjust.html)


In [ ]:
### BEGIN SOLUTION


### END SOLUTION

### 2c. Analysis Question

**Question 1:** Which pairs of columns are easier to read as scatter plots and which are easier to read as line graphs? Why?


**Answer 1:**


## Task 3: Submit the Lab on Google Classroom

Follow the expected lab submission instructions on the lab website.
